//! Requirements traceability helpers (R10).
//!
//! Requirements *of the modelled system* are named traits whose doc comment
//! starts with the requirement ID, with the required characteristics as
//! supertraits and a blanket impl (trait aliases are not stable). The
//! [`crate::requirement!`] macro generates the pattern; because the blanket
//! impl means no source line ever states `impl ReqNNN for ConcreteType`
//! (F-020), each satisfying type carries a doc tag **plus** a compile-checked
//! assertion generated by the macro's `assert = …` helper.
//!
//! `model-core` itself defines no requirements: it is infrastructure, and the
//! workspace `trace.sh` reports "no requirements defined" for it. The pattern
//! below is for the downstream modelling crates.
//!
//! ## The tagging convention (R10, F-021) — enforced by `trace.sh` in CI
//!
//! 1. A requirement trait's doc comment **first line** is
//!    `/// REQ-NNN: <one sentence>.` — IDs are `REQ-` + exactly three digits,
//!    sequential, never reused.
//! 2. Tags are **case-sensitive** (`Verifies:`, `Satisfies:`) and live only
//!    in three-slash `///` doc comments directly above the item; anything in
//!    `//`, `////`, `//!`, `/* */` or string literals is ignored by design,
//!    so IDs may be mentioned freely in prose.
//! 3. Every type or process claimed to satisfy a requirement carries
//!    `/// Satisfies: REQ-NNN` (comma-separated for several) as its own doc
//!    line, backed in the same file by the compile-checked assertion
//!    `const _: () = assert_reqNNN::<TheType>();` (the [`crate::satisfies!`]
//!    macro) — the tag is for grep; the assertion is for truth. A stale tag
//!    is a compile error naming the exact missing characteristic, fired at
//!    type-check time (unaffected by the R4 post-monomorphization caveat).
//! 4. Every test is tagged `/// Verifies: REQ-NNN` — one `Verifies:` line
//!    per test, several IDs comma-separated on that line. `trace.sh` warns
//!    (and fails CI) on requirements with no verifying test, unknown IDs,
//!    and near-miss tags (e.g. lowercase `verifies:`).
//! 5. Requirement bounds stay on the same line as the `fn` name (grep has no
//!    scope awareness).
//! 6. No direct `impl ReqNNN for Type` — the blanket impl inside the macro
//!    is the only impl.
//!
//! ## Usage (runs as a doc-test)
//!
//! The `/// REQ-NNN:` line is written **literally at the invocation site**,
//! inside the macro braces, immediately above the `trait` line — that is what
//! keeps it visible to `trace.sh`'s grep (F-021). The supertrait bounds are
//! parenthesised (a stable `macro_rules!` parsing restriction: `+`-separated
//! path fragments cannot be matched directly).
//!
//! ```
//! trait M8 {}
//! trait Steel {}
//!
//! model_core::requirement! {
//!     /// REQ-001: Fastening bolts must be M8 steel.
//!     pub trait Req001FasteningBolt: (M8 + Steel);
//!     assert = assert_req001;
//! }
//!
//! /// A hex-head M8 steel bolt.
//! pub struct HexBolt;
//! impl M8 for HexBolt {}
//! impl Steel for HexBolt {}
//!
//! // In a real modelling crate this line sits under the type's doc tag for
//! // REQ-001; the assertion keeps the tag honest (F-020).
//! model_core::satisfies!(assert_req001, HexBolt);
//!
//! // Requirements are used as bounds in process signatures (R10), never as
//! // concrete types (F-019).
//! fn fasten<B: Req001FasteningBolt>(bolt: B) -> B {
//!     bolt
//! }
//!
//! fn main() {
//!     let bolt = fasten(HexBolt);
//!     let _accounted = bolt;
//! }
//! ```
//!
//! A stale satisfaction claim is a type-check-time compile error naming the
//! missing characteristic (here `HexBolt` is not `Steel`):
//!
//! ```compile_fail
//! trait M8 {}
//! trait Steel {}
//!
//! model_core::requirement! {
//!     /// REQ-001: Fastening bolts must be M8 steel.
//!     pub trait Req001FasteningBolt: (M8 + Steel);
//!     assert = assert_req001;
//! }
//!
//! pub struct HexBolt;
//! impl M8 for HexBolt {}
//! // impl Steel for HexBolt {}   <- the claim below is now stale...
//!
//! model_core::satisfies!(assert_req001, HexBolt); // ...and fails to compile
//!
//! fn main() {}
//! ```

/// Defines one R10 requirement: the named requirement trait (its `/// REQ-NNN:`
/// doc line written literally at the invocation site, so `trace.sh` sees it),
/// the blanket impl, and the per-requirement `const fn` assertion helper used
/// by [`crate::satisfies!`].
///
/// See the [module docs](crate::requirement) for the full tagging convention
/// and a worked example. Grammar:
///
/// `requirement! { /// REQ-NNN: <sentence>. <vis> trait ReqNNNName: (<bounds>); assert = assert_reqNNN; }`
#[macro_export]
macro_rules! requirement {
    (
        $(#[$meta:meta])*
        $vis:vis trait $Req:ident: ( $($bound:tt)+ );
        assert = $assert_fn:ident;
    ) => {
        $(#[$meta])*
        ///
        /// Requirement trait (R10): satisfied through its blanket impl by any
        /// type with the required characteristics; used as a bound in process
        /// signatures, never as a concrete type (F-019).
        $vis trait $Req: $($bound)+ {}

        // The blanket impl is the ONLY impl (R10 rule 6); satisfaction is a
        // fact the trait solver knows, which is why satisfying types carry a
        // compile-checked doc tag (F-020).
        impl<T: $($bound)+> $Req for T {}

        /// Compile-checked backing for this requirement's satisfaction doc
        /// tags (R10, F-020): planting `const _: () = ` this fn
        /// `::<TheType>();` next to the tag makes a stale tag a
        /// type-check-time compile error naming the exact missing
        /// characteristic.
        #[allow(dead_code)]
        $vis const fn $assert_fn<T: $Req>() {}
    };
}

/// Plants the compile-checked assertion backing a requirement-satisfaction
/// doc tag (R10, F-020): `satisfies!(assert_req001, HexBolt)` expands to
/// `const _: () = assert_req001::<HexBolt>();`.
///
/// Place it in the same file as the tagged type, directly below it. A stale
/// tag then fails to compile at type-check time, naming the requirement
/// trait, the offending type and the missing characteristic.
///
/// The helper's name is a bare identifier (a stable `macro_rules!` parsing
/// restriction: a path fragment cannot be followed by a turbofish), so import
/// the assert fn if the requirement lives in another module.
#[macro_export]
macro_rules! satisfies {
    ($assert_fn:ident, $Type:ty) => {
        const _: () = $assert_fn::<$Type>();
    };
}
