#!/usr/bin/env python3
"""Generates model-core/src/nat/aliases.rs (type aliases N0..N1000).

Adapted from experiments/exp01-type-level-numbers/tools/gen_aliases.py.

Stable `macro_rules!` cannot synthesize identifiers (FINDINGS.md F-013; the
`paste` crate is a forbidden dependency, R8, and `macro_metavar_expr_concat`
is nightly-only), so the alias *names* N0..N1000 must literally exist in the
source. This script writes them out once; the macro in the generated file does
the structural work. The committed output is source (R12): re-run this script
after changing MAX, and commit the result.
"""

import os

MAX = 1000
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "model-core", "src", "nat", "aliases.rs")


def peano() -> str:
    lines = [
        "//! Aliases `N0`..=`N{}` for the Peano type-level naturals (R12).".format(MAX),
        "//!",
        "//! GENERATED by tools/gen_aliases.py - do not edit by hand; re-run the",
        "//! generator and commit its output instead (the output is source, R12).",
        "//!",
        "//! Merely *defining* an alias is lazy and free at any size; the cost of a",
        "//! deep number lands where it is used (FINDINGS.md F-010, F-011). Note",
        "//! that compiler diagnostics erase these aliases and print the expanded",
        "//! `Succ<...>` chains (F-009).",
        "",
        "use super::{Succ, Zero};",
        "",
        "/// Defines each alias as the successor of the previous one.",
        "/// Deliberately non-recursive (a single repetition), so defining",
        "/// 1000 aliases does not consume macro recursion depth.",
        "macro_rules! nats {",
        "    ($($prev:ident => $cur:ident;)*) => {",
        "        $(",
        "            /// A type-level natural number (generated alias).",
        "            pub type $cur = Succ<$prev>;",
        "        )*",
        "    };",
        "}",
        "",
        "/// The type-level natural number 0 (alias for [`Zero`]).",
        "pub type N0 = Zero;",
        "",
        "nats! {",
    ]
    for i in range(1, MAX + 1):
        lines.append("    N{} => N{};".format(i - 1, i))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    with open(OUT, "w") as f:
        f.write(peano())
    print("wrote {} (MAX = {})".format(os.path.normpath(OUT), MAX))


if __name__ == "__main__":
    main()
