//! # pilot-workshop — the downstream pilot model
//!
//! A complete small model of a workshop, built on `model-core` and exercising
//! every part of it: a steel sheet is cut into plate blanks, the plates are
//! drilled (a person, a drill and a slice of the person's time budget), and
//! the drilled plates are fastened into an assembly with four catalogue bolts
//! taken from a `BoltBox` supplier. Swarf from cutting and drilling goes to a
//! `SwarfBin` consumer and on to waste disposal at the system boundary;
//! labour goes to a boundary ledger; the assembly ships to a customer.
//!
//! ## Module map
//!
//! | Module | Contents |
//! |---|---|
//! | [`characteristics`] | Marker characteristic traits (R6): `IsBolt`, `M8`, `Steel`, `Length15mm`, `Drilled`, `SwarfConsumer`, … |
//! | [`catalogue`] | The parameterized bolt catalogue `Bolt<Size, Material, Length>` with kind traits and one-line bridging impls (R6); the `BoltBox` supplier and its sealed fill machinery (R12) |
//! | [`requirements`] | The three modelled-system requirements (REQ-001, REQ-002, REQ-003) as R10 requirement traits via `model_core::requirement!` |
//! | [`resources`] | The sealed resource family (R1): `SteelSheet`, `Plate`/`DrilledPlate`, `Swarf`, `Drill`, `Assembly`, the `SwarfBin` and `Customer` consumers, with `boundary` and `processes` child modules (F-006, F-031) |
//!
//! ## Conservation regime (R1)
//!
//! This crate carries the full obligations listed in `model-core`'s crate
//! docs: `recursion_limit`, `forbid(unsafe_code)`, the must-use/underscore
//! lints, tripwire `Drop`s on every consumable (generated by the kernel
//! macros), and CI clippy under `-D warnings` with the workspace
//! `clippy.toml` ban list. Never write `let _ = <resource>`, and ignore
//! compiler fix-its suggesting borrows, clones or drops (F-007).
//!
//! ## Traceability (R10)
//!
//! The three requirements are defined in [`requirements`] and reported by the
//! workspace `trace.sh` (a CI gate). Satisfying types and processes carry
//! compile-check-backed doc tags; tests are tagged with the requirement IDs
//! they verify.

#![recursion_limit = "2048"]
#![forbid(unsafe_code)]
#![deny(unused_must_use)]
#![deny(let_underscore_drop)]
#![warn(missing_docs)]

pub mod catalogue;
pub mod characteristics;
pub mod requirements;
pub mod resources;
