//! # pilot-workshop — the downstream pilot model
//!
//! A complete small model of a workshop, built on `model-core` and exercising
//! every part of it: a steel sheet is cut into plate blanks, the plates are
//! drilled (a person, a drill and a slice of the person's time budget), and
//! the drilled plates are fastened into an assembly with four catalogue bolts
//! taken from a `BoltBox` supplier. Swarf from cutting and drilling goes to a
//! `SwarfBin` consumer and on to waste disposal at the system boundary;
//! labour is recorded into per-branch execution histories merged at the join
//! (R16); the assembly ships to a customer.
//!
//! ## Module map
//!
//! | Module | Contents |
//! |---|---|
//! | [`characteristics`] | Marker characteristic traits (R6): `IsBolt`, `M8`, `Steel`, `Length15mm`, `Drilled`, `SwarfConsumer`, plus the R18 qualification/safety markers `CertifiedDriller` and `Fitted` |
//! | [`catalogue`] | The parameterized bolt catalogue `Bolt<Size, Material, Length>` with kind traits and one-line bridging impls (R6); the `BoltBox` supplier and its sealed fill machinery (R12) |
//! | [`requirements`] | The five modelled-system requirements (REQ-001..REQ-005) as R10 requirement traits via `model_core::requirement!`, each with a REQ-phrased `on_unimplemented` (R10 rule 8, F-044) |
//! | [`resources`] | The sealed resource family (R1): `SteelSheet`, `Plate`/`DrilledPlate`, `Swarf`, `Drill`, `Assembly`, the `SwarfBin` and `Customer` consumers — plus the R17 failure states (`ScrapPlate`, `BrokenDrillBit`), the `DrillOutcome` token and the fallible drilling step, and the R18 safety states (`MachineGuard`/`FittedGuard`) — with `boundary` and `processes` child modules (F-006, F-031) |
//! | [`flows`] | Fallible-flow compositions (R17): both-arms convergence and the bounded repair-and-retry with its `RetryOutcome` enum (F-046, F-050) |
//! | [`money`] | Money as a conserved dimension (R19): `Money`/`Account`, the exact-price `Vendor`, and the `purchase` process with change as an R3 split (F-051) |
//!
//! ## Conservation regime (R1)
//!
//! This crate carries the full obligations listed in `model-core`'s crate
//! docs: `recursion_limit`, `forbid(unsafe_code)`, the must-use/underscore
//! lints, tripwire `Drop`s on every consumable (generated by the kernel
//! macros), and CI clippy under `-D warnings` with the workspace
//! `clippy.toml` ban list. Never write `let _ = <resource>`, and ignore
//! compiler fix-its suggesting borrows, clones or drops (F-007).
//!
//! ## Traceability (R10)
//!
//! The five requirements are defined in [`requirements`] and reported by the
//! workspace `trace.sh` (a CI gate). Satisfying types and processes carry
//! compile-check-backed doc tags; tests are tagged with the requirement IDs
//! they verify.

#![recursion_limit = "2048"]
#![forbid(unsafe_code)]
#![deny(unused_must_use)]
#![deny(let_underscore_drop)]
#![warn(missing_docs)]

pub mod catalogue;
pub mod characteristics;
pub mod flows;
pub mod money;
pub mod requirements;
pub mod resources;
