//! Requirements of the modelled workshop system (R10).
//!
//! Each requirement is a named trait generated by `model_core::requirement!`:
//! the required characteristics are supertraits, a blanket impl is the only
//! impl, and a per-requirement `const fn` assertion backs every satisfaction
//! doc tag (F-020). The `/// REQ-NNN:` definition lines below are written
//! literally at the invocation sites so the workspace `trace.sh` sees them
//! (F-021); the report runs as a CI gate and fails on any requirement with no
//! verifying test.
//!
//! Requirements are used **only as bounds** in process signatures (F-019) —
//! see `resources::processes::fasten` (REQ-001, REQ-002) and
//! `resources::processes::discard_swarf` (REQ-003).

use crate::characteristics::{Drilled, IsBolt, Length15mm, M8, Steel, SwarfConsumer};

model_core::requirement! {
    /// REQ-001: Fastening bolts must be M8 steel, 15 mm long.
    pub trait Req001FasteningBolt: (IsBolt + M8 + Steel + Length15mm);
    assert = assert_req001;
}

model_core::requirement! {
    /// REQ-002: Plates must be drilled before they are fastened.
    pub trait Req002DrilledBeforeFastening: (Drilled);
    assert = assert_req002;
}

model_core::requirement! {
    /// REQ-003: All swarf must reach a dedicated swarf waste consumer.
    pub trait Req003SwarfWasteConsumer: (SwarfConsumer);
    assert = assert_req003;
}
