//! # cs1-pot-of-tea — case study CS-1: making a pot of tea
//!
//! The first spec→model round trip: this crate implements, downstream of
//! `model-core`, the agreed natural-language specification
//! `case-studies/cs1-pot-of-tea/SPEC.md` (v0.2). One person makes one pot of
//! tea in a kitchen with an electric kettle: continuous resources (water,
//! energy, time) dominate, the flow has one genuine ordering freedom (the
//! kettle boils with **no person**, so the pot can be loaded before or while
//! it boils), and the spent teabags leave through the food-waste bin's sealed
//! disposal path (P5, F-039).
//!
//! ## Module map
//!
//! | Module | Contents |
//! |---|---|
//! | [`characteristics`] | Characteristic traits (R6): [`characteristics::Boiling`] and [`characteristics::LoadedToBrew`] (which carry the water/energy and bag-mass quantities, R6/R7, plus the permit-gated conserving extraction), and the sink markers [`characteristics::FoodWasteConsumer`] and [`characteristics::KitchenAirSink`] |
//! | [`requirements`] | The four modelled-system requirements of SPEC.md §2 as R10 requirement traits via `model_core::requirement!`, each with a REQ-phrased `on_unimplemented` (R10 rule 8, F-044). The workspace trace namespace is global and the pilot owns REQ-001..REQ-005, so CS-1 continues the sequence: REQ-006..REQ-009 here are SPEC.md's REQ-001..REQ-004 in order (the mapping is spelled out in [`requirements`]) |
//! | [`resources`] | The sealed resource family (R1): the water/kettle/pot states (one type per state, R9), teabags dry and spent, the teabag-box supplier, the food-waste bin (a contents-keeping consumer, F-016/F-034) and the boundary sinks — with `boundary` and `processes` child modules (F-006, F-031) |
//!
//! Flows (SPEC.md §6) are integration tests: `tests/flows.rs` composes the
//! processes P1..P5 in both agreed valid orders and accounts for everything
//! at flow end (R1, R9).
//!
//! ## Conservation regime (R1)
//!
//! This crate carries the full obligations listed in `model-core`'s crate
//! docs: `recursion_limit`, `forbid(unsafe_code)`, the must-use/underscore
//! lints, tripwire `Drop`s on every consumable (generated by the kernel
//! macros), and CI clippy under `-D warnings` with the workspace
//! `clippy.toml` ban list. Never write `let _ = <resource>`, and ignore
//! compiler fix-its suggesting borrows, clones or drops (F-007).
//!
//! ## The person's time budget (R15)
//!
//! The person enters at the boundary with the SPEC's 300 000 ms budget and
//! every person-process in the flow has an **adjacent** `draw_time` whose
//! labour is recorded into the single `History` attributed to the process
//! name (R16, F-048). Overspending the budget is a compile error like any
//! overdraw (E0080 at monomorphization, invisible to `cargo check`, F-001).
//! Regression — 30 000 ms of kettle-filling cannot come out of a 20 000 ms
//! budget:
//!
//! ```compile_fail
//! use model_core::common::boundary::new_person;
//! use model_core::common::processes::draw_time;
//!
//! let person = new_person::<20_000>();
//! let (labour, person) = draw_time::<30_000, 0, 20_000>(person);
//! ```
//!
//! ## Traceability (R10)
//!
//! The four requirements are defined in [`requirements`] and reported by the
//! workspace `trace.sh` (a CI gate). Satisfying types and processes carry
//! compile-check-backed doc tags; tests are tagged with the requirement IDs
//! they verify.

#![recursion_limit = "2048"]
#![forbid(unsafe_code)]
#![deny(unused_must_use)]
#![deny(let_underscore_drop)]
#![warn(missing_docs)]

pub mod characteristics;
pub mod requirements;
pub mod resources;
