//! Requirements of the modelled tea-making system (R10) — SPEC.md §2.
//!
//! **Id mapping (a deviation from SPEC.md, recorded in the build report):**
//! SPEC.md §2 numbers these requirements REQ-001..REQ-004, but the workspace
//! `trace.sh` keys requirement ids globally and the pilot already owns
//! REQ-001..REQ-005 — re-using the spec's ids silently merges CS-1's rows
//! into the pilot's requirements while the gate stays green (the dangerous
//! F-037 direction). R10's "never reused" therefore applies workspace-wide:
//! CS-1 continues the sequence as REQ-006..REQ-009, mapping
//! REQ-006 ← spec REQ-001 (boiling water), REQ-007 ← spec REQ-002 (exactly
//! 3 teabags), REQ-008 ← spec REQ-003 (spent bags to the food-waste bin),
//! REQ-009 ← spec REQ-004 (waste heat to the kitchen air).
//!
//! Each requirement is a named trait generated by `model_core::requirement!`:
//! the required characteristic is a supertrait, the blanket impl is the only
//! impl, and a per-requirement `const fn` assertion backs every satisfaction
//! doc tag (F-020). The `/// REQ-NNN:` definition lines below are written
//! literally at the invocation sites so the workspace `trace.sh` sees them
//! (F-021); the report runs as a CI gate and fails on any requirement with no
//! verifying test.
//!
//! **Every requirement trait carries its own one-line
//! `#[diagnostic::on_unimplemented]`** phrased as the requirement and naming
//! its REQ id, passed through `requirement!`'s meta slot (R10 rule 8, F-044):
//! a failing marker's own attribute is ignored when the marker fails as a
//! supertrait obligation of a requirement bound — only the root obligation's
//! message is shown — so the requirement trait's message is the one modellers
//! will see. Marker-level attributes stay too, for direct marker bounds.
//!
//! Requirements are used **only as bounds** in process signatures (F-019) —
//! see `resources::processes::pour_and_brew` (REQ-006 on the kettle, REQ-007
//! on the pot, REQ-008 on the bin, REQ-009 on the air),
//! `resources::processes::vent_heat` (REQ-009) and
//! `resources::processes::empty_bin` (REQ-008, restated as a where-clause on
//! the concrete bin for traceability).

use crate::characteristics::{Boiling, FoodWasteConsumer, KitchenAirSink, LoadedToBrew};

model_core::requirement! {
    /// REQ-006: Tea must be brewed with boiling water (only the boiling state of the kettle can be poured into the pot).
    /// (SPEC.md §2 numbers this requirement REQ-001; see the id mapping in the module docs.)
    #[diagnostic::on_unimplemented(message = "this kettle may not be poured into the pot: `{Self}` is not at the boil (REQ-006)", label = "REQ-006: tea must be brewed with boiling water", note = "boiling is a process state (R9): `boil` turns a `FilledKettle` into a `BoilingKettle` - only that state can be poured")]
    pub trait Req006PouredAtTheBoil: (Boiling);
    assert = assert_req006;
}

model_core::requirement! {
    /// REQ-007: The pot must be loaded with exactly 3 teabags before brewing.
    /// (SPEC.md §2 numbers this requirement REQ-002; see the id mapping in the module docs.)
    #[diagnostic::on_unimplemented(message = "this pot may not be brewed: `{Self}` is not a pot loaded with exactly 3 teabags (REQ-007)", label = "REQ-007: the pot must be loaded with exactly 3 teabags before brewing", note = "loading is a process (R9): `load_pot` takes 3 bags from the teabag box and turns a `Teapot` into a `LoadedPot` - the loaded state exists only at exactly 3 bags")]
    pub trait Req007LoadedWithThreeBags: (LoadedToBrew);
    assert = assert_req007;
}

model_core::requirement! {
    /// REQ-008: All spent teabags must reach the food-waste bin.
    /// (SPEC.md §2 numbers this requirement REQ-003; see the id mapping in the module docs.)
    #[diagnostic::on_unimplemented(message = "spent teabags may not go here: `{Self}` is not the food-waste bin (REQ-008)", label = "REQ-008: all spent teabags must reach the food-waste bin", note = "the dedicated consumer is the `FoodWasteBin` (any fill state); it leaves its contents to the council collection only through `empty_bin` (the sealed F-039 disposal path)")]
    pub trait Req008FoodWasteBinOnly: (FoodWasteConsumer);
    assert = assert_req008;
}

model_core::requirement! {
    /// REQ-009: All waste heat must be accounted to the kitchen-air sink.
    /// (SPEC.md §2 numbers this requirement REQ-004; see the id mapping in the module docs.)
    #[diagnostic::on_unimplemented(message = "waste heat may not go here: `{Self}` is not the kitchen-air sink (REQ-009)", label = "REQ-009: all waste heat must be accounted to the kitchen-air sink", note = "the kitchen air (`KitchenAir`) is the placeholder unbounded sink for waste heat (R15)")]
    pub trait Req009HeatToKitchenAir: (KitchenAirSink);
    assert = assert_req009;
}
