//! Requirements of the modelled two-site system owned by supply (R10) —
//! SPEC §2.
//!
//! The workspace `trace.sh` keys requirement ids globally (F-053): the pilot
//! and CS-1..4 own REQ-001..REQ-022, so CS-5 starts at REQ-023 — exactly as
//! SPEC §2 allocates, so no spec↔code id mapping is needed. The five CS-5
//! requirements are split by subsystem ownership (SPEC §3): REQ-023 and
//! REQ-024 live here, REQ-027 in `cs5-logistics`, REQ-025 and REQ-026 in
//! `cs5-works`.
//!
//! Each requirement is a named trait generated by `model_core::requirement!`:
//! the required characteristic is a supertrait, the blanket impl is the only
//! impl, and a per-requirement `const fn` assertion backs every satisfaction
//! doc tag (F-020). **Every requirement trait carries its own one-line
//! `#[diagnostic::on_unimplemented]`** phrased as the requirement and naming
//! its REQ id (R10 rule 8, F-044).
//!
//! Requirements are used **only as bounds** in process signatures (F-019) —
//! REQ-023 on [`crate::resources::processes::sell_component`]'s vendor (and
//! restated on `cs5-logistics`' P3), REQ-024 on
//! [`crate::resources::processes::exchange`]'s desk.

use crate::characteristics::{ExchangeDesk, PricedInEuroCents};

model_core::requirement! {
    /// REQ-023: Foreign purchases must be paid in the supplier's currency (the vendor accepts euro cents only).
    #[diagnostic::on_unimplemented(message = "this purchase may not be made here: `{Self}` is not the vendor selling in its own currency (REQ-023)", label = "REQ-023: foreign purchases must be paid in the supplier's currency", note = "the vendor's `Consumer` impl exists only at `Euros<2340>` (exact price, F-051): a GBP payment is a type error, and euro cents come only from the bureau exchange (REQ-024)")]
    pub trait Req023PaidInEuroCents: (PricedInEuroCents);
    assert = assert_req023;
}

model_core::requirement! {
    /// REQ-024: Currency may be exchanged only at the bureau, at its stated rate.
    #[diagnostic::on_unimplemented(message = "currency may not be exchanged here: `{Self}` is not the bureau (REQ-024)", label = "REQ-024: currency may be exchanged only at the bureau, at its stated rate", note = "exchange is value-equivalence at the stated integer rate, boundary-only (R19/F-052): `exchange` const-asserts OUT x 100 == IN x 117, so a non-exact amount has no compiling OUT")]
    pub trait Req024ExchangeAtTheBureau: (ExchangeDesk);
    assert = assert_req024;
}
