//! # cs6-bread-batch — case study CS-6: baking a batch of bread
//!
//! The first crate started from a **`specgen` scaffold** (R22): the agreed
//! natural-language specification `case-studies/cs6-bread-batch/SPEC.md`
//! (v0.2) was run once through `tools/spec-gen`, and the one-shot scaffold —
//! every item carrying a breadcrumb to its SPEC.md §/line, every
//! under-determined decision enumerated as a SPEC-HOLE (U-01..U-14) — was
//! promoted to hand-maintained in the same change that commits it. Every
//! hole is resolved below in the house style; the breadcrumb doc comments
//! are kept where they remain true.
//!
//! One baker makes two loaves of bread in a home kitchen. CS-6's domain was
//! chosen for emitter-path breadth (SPEC.md §1): a discrete supplier
//! exhausted to its empty container (the yeast box), continuous draws in
//! three units (g, J, ms), multi-quantity states (a baked loaf carries mass
//! *and* embodied energy), a reusable with its own quantity-bearing state
//! chain (the greased tin), and **fallibility without rework** (R17) — a
//! scorched loaf is final, where CS-2's failures had provisioned retries.
//!
//! ## Module map
//!
//! | Module | Contents |
//! |---|---|
//! | [`characteristics`] | Characteristic traits (R6): the sealed, quantity-carrying [`characteristics::Proved`] and [`characteristics::Greased`] (permit-gated conserving extractions, F-054), and the sink markers [`characteristics::BakedOnlyHousehold`] and [`characteristics::ScorchedLoafCompost`] |
//! | [`requirements`] | The four modelled-system requirements of SPEC.md §2 as R10 requirement traits via `model_core::requirement!`, each with a REQ-phrased `on_unimplemented` (R10 rule 8, F-044). The workspace trace namespace is global (F-053): CS-1..CS-5 end at REQ-027, so CS-6 owns REQ-028..031 exactly as SPEC.md §2 numbers them |
//! | [`resources`] | The sealed resource family (R1): the dough/loaf/tin states (one type per state, R9, masses and embodied energy in the types), the yeast box supplier exhausted to its empty shell, the pantry containers, the `BakeOutcome` token (R17), and the unbounded household/compost/atmosphere/recycling sinks — with `boundary` and `processes` child modules (F-006, F-031) |
//! | [`flows`] | The batch flow (R17/F-050): both §6 orders, each returning the `#[must_use]` four-combination outcome grouping [`flows::BatchOutcome`] beside the shared [`flows::KitchenAtRest`] — the four combinations differ only in where the loaves went (F-046/F-050) |
//!
//! Flows (SPEC.md §6) are exercised as integration tests: `tests/flows.rs`
//! drives all four outcome combinations through [`flows::bake_batch`] (and
//! the tins-first ordering variant) and accounts for everything at each
//! combination's end (R1, R9).
//!
//! ## Conservation regime (R1)
//!
//! This crate carries the full obligations listed in `model-core`'s crate
//! docs: `recursion_limit`, `forbid(unsafe_code)`, the must-use/underscore
//! lints, tripwire `Drop`s on every consumable (generated by the kernel
//! macros), and CI clippy under `-D warnings` with the workspace
//! `clippy.toml` ban list. Never write `let _ = <resource>`, and ignore
//! compiler fix-its suggesting borrows, clones, drops or `.expect(…)`
//! (F-007).
//!
//! ## The baker's time budget (R15)
//!
//! The baker enters at the boundary with the SPEC's 7 200 000 ms (2 h)
//! budget. Every process in the flow has an **adjacent** `draw_time` whose
//! labour is recorded into the single `History` attributed to the process
//! name (R16, F-048); each bake's draw happens *before* the fallible branch,
//! so a scorch costs the same time as a good bake (R17). Overspending the
//! budget is a compile error like any overdraw (E0080 at monomorphization,
//! invisible to `cargo check`, F-001). Regression — a 3 600 000 ms prove
//! cannot come out of a 2 100 000 ms remainder:
//!
//! ```compile_fail
//! use model_core::common::boundary::new_person;
//! use model_core::common::processes::draw_time;
//!
//! let baker = new_person::<2_100_000>();
//! let (labour, baker) = draw_time::<3_600_000, 0, 2_100_000>(baker);
//! ```
//!
//! Overdrawing a pantry container is the same error class (R15): the 1 500 g
//! flour bag cannot give 1 600 g —
//!
//! ```compile_fail
//! use cs6_bread_batch::resources::boundary::new_pantry_bag;
//! use cs6_bread_batch::resources::processes::draw_flour;
//!
//! let bag = new_pantry_bag();
//! let (flour, bag) = draw_flour::<1_600, 0, 1_500>(bag);
//! ```
//!
//! ## Traceability (R10)
//!
//! The four requirements are defined in [`requirements`] and reported by the
//! workspace `trace.sh` (a CI gate). SPEC.md §5 deliberately has P3 (prove)
//! and P4 (grease) satisfy **nothing** — they *enable* REQ-028 and REQ-029
//! by producing the satisfying states, and the requirement bounds sit on
//! `divide_and_shape` and `bake` instead. Tests are tagged with the
//! requirement IDs they verify.

#![recursion_limit = "2048"]
#![forbid(unsafe_code)]
#![deny(unused_must_use)]
#![deny(let_underscore_drop)]
#![warn(missing_docs)]

pub mod characteristics;
pub mod flows;
pub mod requirements;
pub mod resources;
