//! Requirements of the modelled bread-batch system (R10) — SPEC.md §2.
//!
//! Started from the specgen scaffold of SPEC.md (R22) and hand-maintained
//! since: the scaffold emitted the four traits with REQ-phrased
//! `on_unimplemented` messages; the characteristic placements, the curated
//! wording and the `satisfies!` assertions (the scaffold's SPEC-HOLE U-06)
//! are hand design, following CS-2.
//!
//! The workspace `trace.sh` keys requirement ids globally (F-053): the pilot
//! owns REQ-001..005, CS-1..CS-5 own REQ-006..027, so CS-6 continues the
//! sequence at REQ-028 — exactly as SPEC.md §2 allocates them, so no
//! spec↔code id mapping is needed.
//!
//! Each requirement is a named trait generated by `model_core::requirement!`:
//! the required characteristic is a supertrait, the blanket impl is the only
//! impl, and a per-requirement `const fn` assertion backs every satisfaction
//! doc tag (F-020). The `/// REQ-NNN:` definition lines below are written
//! literally at the invocation sites so the workspace `trace.sh` sees them
//! (F-021); the report runs as a CI gate and fails on any requirement with no
//! verifying test.
//!
//! **Every requirement trait carries its own one-line
//! `#[diagnostic::on_unimplemented]`** phrased as the requirement and naming
//! its REQ id, passed through `requirement!`'s meta slot (R10 rule 8, F-044):
//! a failing marker's own attribute is ignored when the marker fails as a
//! supertrait obligation of a requirement bound — only the root obligation's
//! message is shown — so the requirement trait's message is the one modellers
//! will see. Marker-level attributes stay too, for direct marker bounds.
//!
//! Requirements are used **only as bounds** in process signatures (F-019) —
//! see `resources::processes::divide_and_shape` (REQ-028 on the dough),
//! `resources::processes::bake` (REQ-029 on the tin) and the
//! `flows::bake_batch*` consumer parameters (REQ-030 on the household,
//! REQ-031 on the compost stream). SPEC.md §5 deliberately claims **no**
//! satisfaction for P3 (prove) and P4 (grease the tins): those processes
//! *enable* REQ-028 and REQ-029 by producing the satisfying states, and their
//! `Satisfies:` lines read `—` — so no tags sit on them here.

use crate::characteristics::{BakedOnlyHousehold, Greased, Proved, ScorchedLoafCompost};

model_core::requirement! {
    /// REQ-028: Dough may be divided and shaped only once it is proved.
    #[diagnostic::on_unimplemented(message = "this dough may not be divided and shaped: `{Self}` is not proved dough (REQ-028)", label = "REQ-028: dough may be divided and shaped only once it is proved", note = "proving is a process (one type per state, R9): `prove` turns a `KneadedDough` into a `ProvedDough` - only that state can be shaped")]
    pub trait Req028ProvedBeforeShaping: (Proved);
    assert = assert_req028;
}

model_core::requirement! {
    /// REQ-029: The oven may bake only a loaf seated in a greased tin.
    #[diagnostic::on_unimplemented(message = "this tin may not go in the oven: `{Self}` is not a greased tin (REQ-029)", label = "REQ-029: the oven may bake only a loaf seated in a greased tin", note = "greasing is a process (one type per state, R9): `grease_tins` turns two `CleanTin`s into `GreasedTin`s - only that state can be baked in")]
    pub trait Req029GreasedTinInTheOven: (Greased);
    assert = assert_req029;
}

model_core::requirement! {
    /// REQ-030: The household accepts only baked loaves - a scorched loaf may not be handed over.
    #[diagnostic::on_unimplemented(message = "loaves may not be handed over here: `{Self}` is not the household accepting only baked loaves (REQ-030)", label = "REQ-030: the household accepts only baked loaves", note = "the household's `Consumer` impl exists for `BakedLoaf` alone (R15): a scorched loaf has no consumer there and must reach the compost stream instead (REQ-031)")]
    pub trait Req030BakedLoavesOnly: (BakedOnlyHousehold);
    assert = assert_req030;
}

model_core::requirement! {
    /// REQ-031: Every scorched loaf must reach the compost stream.
    #[diagnostic::on_unimplemented(message = "scorched loaves may not go here: `{Self}` is not the compost stream (REQ-031)", label = "REQ-031: every scorched loaf must reach the compost stream", note = "the compost stream is the only consumer of `ScorchedLoaf` in the model (R15): a scorched bake is final (no rework, R17) and composting is its one exit")]
    pub trait Req031ScorchedToCompost: (ScorchedLoafCompost);
    assert = assert_req031;
}
