//! Requirements of the modelled stores-plus-line system (R10) — SPEC.md §2.
//!
//! The workspace `trace.sh` keys requirement ids globally (F-053): the pilot
//! owns REQ-001..REQ-005, CS-1 owns REQ-006..REQ-009, CS-2 owns
//! REQ-010..REQ-014 and CS-3 owns REQ-015..REQ-018, so CS-4 continues the
//! sequence at REQ-019 — exactly as SPEC.md §2 allocates them, so no
//! spec↔code id mapping is needed.
//!
//! Each requirement is a named trait generated by `model_core::requirement!`:
//! the required characteristic is a supertrait, the blanket impl is the only
//! impl, and a per-requirement `const fn` assertion backs every satisfaction
//! doc tag (F-020). The `/// REQ-NNN:` definition lines below are written
//! literally at the invocation sites so the workspace `trace.sh` sees them
//! (F-021); the report runs as a CI gate and fails on any requirement with no
//! verifying test.
//!
//! **Every requirement trait carries its own one-line
//! `#[diagnostic::on_unimplemented]`** phrased as the requirement and naming
//! its REQ id, passed through `requirement!`'s meta slot (R10 rule 8, F-044).
//!
//! Requirements are used **only as bounds** in process signatures (F-019):
//! REQ-019 on the bolt parameter of `resources::processes::join_assembly`
//! (stores) and `cs4-line`'s `fasten`; REQ-020 on the disposal and REQ-022 on
//! the finished-goods store in `resources::processes::reconcile`; REQ-021 on
//! the note parameter `cs4-line`'s `fasten` threads through every cycle.
//! **REQ-019 is additionally — and primarily — the crate edge itself**
//! (SPEC §3): `cs4-line` physically cannot construct any type these
//! characteristics seal (E0451/privacy, proved by `cs4-line`'s trybuild case
//! `tests/ui/line_cannot_mint_materials.rs`).

use crate::characteristics::{DisposalSink, FinishedGoodsStore, ProofOfIssue, StoresIssued};

model_core::requirement! {
    /// REQ-019: Assemblies may be built only from stores-issued materials (provenance: the line cannot mint or source materials itself - enforced by the crate boundary).
    #[diagnostic::on_unimplemented(message = "this may not be built into an assembly: `{Self}` is not a stores-issued material (REQ-019)", label = "REQ-019: assemblies may be built only from stores-issued materials", note = "materials are created only inside cs4-stores and released only by the issue process P1 against a works order; the crate edge makes minting one downstream a privacy error (E0451), and this bound makes smuggling a non-stores type a requirement error")]
    pub trait Req019StoresIssuedMaterial: (StoresIssued);
    assert = assert_req019;
}

model_core::requirement! {
    /// REQ-020: All swarf from a batch must be collected in the line's bin and returned to stores' disposal at batch end.
    #[diagnostic::on_unimplemented(message = "swarf may not leave the model here: `{Self}` is not stores' disposal (REQ-020)", label = "REQ-020: batch swarf is returned to stores' disposal at batch end", note = "during the cycles swarf is collected in the line's bin (fed inside cut and drill); at reconciliation (P6) the full bin is returned and its contents are consumed by stores' `Disposal` - the only exit for swarf")]
    pub trait Req020SwarfToDisposal: (DisposalSink);
    assert = assert_req020;
}

model_core::requirement! {
    /// REQ-021: The line may operate only against a current stores issue note (the subsystem interface evidence, threaded through the batch and reconciled at the end).
    #[diagnostic::on_unimplemented(message = "the line may not operate here: `{Self}` is not a current stores issue note (REQ-021)", label = "REQ-021: the line may operate only against a current stores issue note", note = "the note is minted only by P1 (`issue_materials`), threaded through every batch cycle by `fasten`, and reconciled by P6 (`reconcile`); a flow that never drew materials from stores has nothing to put here")]
    pub trait Req021CurrentIssueNote: (ProofOfIssue);
    assert = assert_req021;
}

model_core::requirement! {
    /// REQ-022: Completed assemblies must be delivered to finished-goods stores.
    #[diagnostic::on_unimplemented(message = "completed assemblies may not go here: `{Self}` is not the finished-goods store (REQ-022)", label = "REQ-022: completed assemblies must be delivered to finished-goods stores", note = "assemblies leave the model only into stores' `FinishedGoods` consumer at reconciliation (P6); it keeps what it consumes, so delivery is counted by its contents")]
    pub trait Req022ToFinishedGoods: (FinishedGoodsStore);
    assert = assert_req022;
}
