//! # cs3-cafe-orders — case study CS-3: café order fulfilment
//!
//! The third spec→model round trip: this crate implements, downstream of
//! `model-core`, the agreed natural-language specification
//! `case-studies/cs3-cafe-orders/SPEC.md` (v0.4, agreed). A small café
//! fulfils one order — a flat white and a pot of tea — with **two staff
//! working genuinely in parallel**. CS-3 is the **concurrency case study**:
//! the first model with two actors, two genuinely disjoint branches
//! (different people, different equipment, different stock), and **per-branch
//! Histories merged at the join into R16's partial order for real** — plus
//! fallible milk steaming with provisioned rework (R17/F-050) and money at
//! the till including a refund on the worst path (R19).
//!
//! ## Module map
//!
//! | Module | Contents |
//! |---|---|
//! | [`characteristics`] | Characteristic traits (R6): [`characteristics::MachineTrained`] (the R18 qualification marker over `Qualified<MachineTraining, MS>`), the sealed [`characteristics::ProofOfPayment`] and [`characteristics::OrderSlot`] (permit-gated conserving extractions, F-054), and the sink/recipient markers [`characteristics::DrainSink`] and [`characteristics::ChangeRecipient`] |
//! | [`requirements`] | The four modelled-system requirements of SPEC.md §2 as R10 requirement traits via `model_core::requirement!`, each with a REQ-phrased `on_unimplemented` (R10 rule 8, F-044). The workspace trace namespace is global (F-053): the pilot owns REQ-001..005, CS-1 owns REQ-006..009 and CS-2 owns REQ-010..014, so CS-3 starts at REQ-015 exactly as SPEC.md §2 numbers it |
//! | [`resources`] | The sealed resource family (R1): stock containers and draws (milk/coffee/water/tea, R15), the drink states (one type per state, R9, masses in the types), money and the till (R19), the `PaymentReceipt` (REQ-017's key), the `SteamOutcome` token (R17), the staff and machine, the `Customer`/`Drain`/`KnockBox` boundary objects — with `boundary` and `processes` child modules (F-006, F-031) |
//! | [`flows`] | **The concurrency demonstration** (R9/R16): two interleavings of the two branches ([`flows::fulfil_order`] and [`flows::fulfil_order_branches_in_turn`]) with identical per-path end states, returning the `#[must_use]` per-path outcome grouping [`flows::OrderOutcome`] (F-046/F-050); the join merges `h_a` and `h_b` into one `Entry::Join` |
//!
//! Flows (SPEC.md §6) are exercised as integration tests: `tests/flows.rs`
//! drives all three paths through both interleavings and accounts for
//! everything at each path's end (R1, R9), asserting the **merged History's
//! Join shape** — branch A's and branch B's event sequences intact and
//! un-interleaved, with per-branch counts 3 + 3 / 4 + 3 / 4 + 4 across the
//! three paths (R16).
//!
//! ## Conservation regime (R1)
//!
//! This crate carries the full obligations listed in `model-core`'s crate
//! docs: `recursion_limit`, `forbid(unsafe_code)`, the must-use/underscore
//! lints, tripwire `Drop`s on every consumable (generated by the kernel
//! macros), and CI clippy under `-D warnings` with the workspace
//! `clippy.toml` ban list. Never write `let _ = <resource>`, and ignore
//! compiler fix-its suggesting borrows, clones, drops or `.expect(…)`
//! (F-007).
//!
//! ## The staff's time budgets (R15/R18)
//!
//! Both staff enter at the boundary with the SPEC's 600 000 ms budgets: the
//! barista already trained (`qualify::<MachineTraining, _>`, the R18
//! placeholder boundary process — REQ-015's subject), the server as a plain
//! `Person`. Every person-process in the flow has an **adjacent** time draw
//! (F-048) whose labour is recorded into **that actor's own branch History**
//! attributed to the process name (R16): `h_a` for the barista, `h_b` for
//! the server — one History per concurrent branch, never a global one, which
//! under strict conservation (R2) would serialize the model and delete the
//! concurrency this case study exists to demonstrate. Each steaming
//! attempt's draw happens *before* the fallible branch, so failure costs the
//! same time as success (R17). Overspending a budget is a compile error like
//! any overdraw (E0080 at monomorphization, invisible to `cargo check`,
//! F-001). Regression — the server's 240 000 ms path cannot come out of a
//! 210 000 ms remainder:
//!
//! ```compile_fail
//! use model_core::common::boundary::new_person;
//! use model_core::common::processes::draw_time;
//!
//! let server = new_person::<600_000>();
//! let (l1, server) = draw_time::<390_000, 210_000, 600_000>(server);
//! let (l2, server) = draw_time::<240_000, 0, 210_000>(server);
//! ```
//!
//! ## Traceability (R10)
//!
//! The four requirements are defined in [`requirements`] and reported by the
//! workspace `trace.sh` (a CI gate). REQ-017's receipt is the **one
//! deliberate cross-branch dependency**: the join consumes evidence only the
//! till branch can mint, which is what makes "hand over before payment"
//! inexpressible rather than merely untested. Tests are tagged with the
//! requirement IDs they verify.

#![recursion_limit = "2048"]
#![forbid(unsafe_code)]
#![deny(unused_must_use)]
#![deny(let_underscore_drop)]
#![warn(missing_docs)]

pub mod characteristics;
pub mod flows;
pub mod requirements;
pub mod resources;
