//! Requirements of the modelled café system (R10) — SPEC.md §2.
//!
//! The workspace `trace.sh` keys requirement ids globally (F-053): the pilot
//! owns REQ-001..REQ-005, CS-1 owns REQ-006..REQ-009 and CS-2 owns
//! REQ-010..REQ-014, so CS-3 continues the sequence at REQ-015 — exactly as
//! SPEC.md §2 allocates them, so no spec↔code id mapping is needed.
//!
//! Each requirement is a named trait generated by `model_core::requirement!`:
//! the required characteristic is a supertrait, the blanket impl is the only
//! impl, and a per-requirement `const fn` assertion backs every satisfaction
//! doc tag (F-020). The `/// REQ-NNN:` definition lines below are written
//! literally at the invocation sites so the workspace `trace.sh` sees them
//! (F-021); the report runs as a CI gate and fails on any requirement with no
//! verifying test.
//!
//! **Every requirement trait carries its own one-line
//! `#[diagnostic::on_unimplemented]`** phrased as the requirement and naming
//! its REQ id, passed through `requirement!`'s meta slot (R10 rule 8, F-044):
//! a failing marker's own attribute is ignored when the marker fails as a
//! supertrait obligation of a requirement bound — only the root obligation's
//! message is shown — so the requirement trait's message is the one modellers
//! will see. Marker-level attributes stay too, for direct marker bounds.
//!
//! Requirements are used **only as bounds** in process signatures (F-019) —
//! see `resources::processes::pull_espresso` (REQ-015 on the barista),
//! `resources::processes::steam_milk` (REQ-016 on the drain),
//! `resources::processes::take_payment` (REQ-018 on the customer) and
//! `resources::processes::hand_over` (REQ-017 on the receipt — the one
//! deliberate cross-branch dependency of this concurrency case study).

use crate::characteristics::{ChangeRecipient, DrainSink, MachineTrained, ProofOfPayment};

model_core::requirement! {
    /// REQ-015: The espresso machine may be operated only by a trained barista.
    #[diagnostic::on_unimplemented(message = "this person may not operate the espresso machine: `{Self}` is not a trained barista (REQ-015)", label = "REQ-015: the espresso machine may be operated only by a trained barista", note = "training is granted at the boundary (R12/R18): `qualify::<MachineTraining, BUDGET>(person)` wraps a `Person` into a `Qualified` barista - the server (a plain `Person`) is refused here")]
    pub trait Req015TrainedBarista: (MachineTrained);
    assert = assert_req015;
}

model_core::requirement! {
    /// REQ-016: Burnt milk must be discarded to the drain - it is never re-steamed or served.
    #[diagnostic::on_unimplemented(message = "burnt milk may not go here: `{Self}` is not the drain (REQ-016)", label = "REQ-016: burnt milk must be discarded to the drain - it is never re-steamed or served", note = "the dedicated sink is the `Drain` (an unbounded placeholder, R15); `steam_milk` feeds burnt milk to it inside the process, so burnt milk never exists loose and the burnt state has no other exit")]
    pub trait Req016BurntMilkToTheDrain: (DrainSink);
    assert = assert_req016;
}

model_core::requirement! {
    /// REQ-017: An order may be handed over only after payment (the join requires the payment receipt from the till branch).
    #[diagnostic::on_unimplemented(message = "the order may not be handed over: `{Self}` is not the payment receipt from the till branch (REQ-017: an order may be handed over only after payment)", label = "REQ-017: an order may be handed over only after payment", note = "the receipt is minted only by `take_payment` (branch B): the join consumes it, so a flow that never takes payment has nothing to hand `hand_over` - the one deliberate cross-branch dependency")]
    pub trait Req017PaymentBeforeHandover: (ProofOfPayment);
    assert = assert_req017;
}

model_core::requirement! {
    /// REQ-018: The customer's change must be returned in full at the till.
    #[diagnostic::on_unimplemented(message = "the change may not go here: `{Self}` is not the customer (REQ-018: the customer's change must be returned in full at the till)", label = "REQ-018: the customer's change must be returned in full at the till", note = "`take_payment` splits the tendered note into the order price and the change (1000 = 700 + 300, const-asserted) and feeds the change to the customer inside the process - the split's second output has only the customer exit")]
    pub trait Req018ChangeInFull: (ChangeRecipient);
    assert = assert_req018;
}
